services:
  web:
    build: .
    container_name: php-apache-node
    ports:
      - "8080:80"
    volumes:
      - C:/xampp/htdocs/CMS-9:/var/www/html
    networks:
      - app_network
    depends_on:
      - db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    command: bash -c "npm install && apache2-foreground"

  db:
    image: mysql:5.7
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2.1
    container_name: phpmyadmin-container
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "8081:80"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  db-data:
